import React, { useEffect, useState } from "react";

import styles from "../..//styles/Services.module.css";

import ServiceModule from "../../components/ServiceCard";
import Spinner from "../../components/Spinner";
import Head from "next/head";
import { getAllServices } from "../../utils/data/getData";

function Services() {
  const [services, setServices] = useState([]);
  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setServices(getAllServices());
      setLoading(false);
    }, 2000);
  }, []);
  return (
    <div>
      <Head>
        <title>Square43 Studio | Services</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="wrapper">
        <h1
          style={{
            animation: `fadeInRight 1s forwards ease-in-out`,
            opacity: 0,
          }}
          className={styles.title}
        >
          Services
        </h1>
        <section className={styles.section}>
          {isLoading ? (
            <Spinner />
          ) : (
            services.map((service, key) => {
              let counter = 300;
              const style = {
                animation: `fadeInUp 1s ${
                  counter * key
                }ms forwards ease-in-out`,
                opacity: 0,
              };
              return (
                <ServiceModule key={key} service={service} style={style} />
              );
            })
          )}
        </section>
      </div>
    </div>
  );
}

export default Services;
