import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Square from "../components/Square";

export default function Home() {
  const [count, setCount] = useState(0);
  const stamps = ["Digital", "Creative", "Studio."];
  const stamps2 = ["Modern", "experience", "for", "tomorrow", "brands."];

  return (
    <div>
      <Head>
        <title>Square43 Studio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div className={styles.Home}>
          <div className={styles.wrapper}>
            <Square />
            <h1 className={styles.title}>Square43</h1>
            <p className={styles.stamp}>
              {stamps2.map((stamp, key) => {
                let counter = 300;
                const style = {
                  animation: `translateUp 1s ${
                    counter * key
                  }ms forwards ease-in-out`,
                  transform: "translateY(100%)",
                };
                return (
                  <span key={key} style={style} className="word">
                    {stamp}&nbsp;
                  </span>
                );
              })}
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
