import React from "react";
import Head from "next/head";

import Hero from "../pages-sections/home/Hero";
import Philosophy from "../pages-sections/home/Philosophy";
import OurServices from "../pages-sections/home/OurServices";
import More from "../pages-sections/home/More";
import Project from "../pages-sections/home/Project";
import Contact from "../pages-sections/home/Contact";
import Square from "../components/Square";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Square43 Studio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Square image="/square-temp.webp" height={560} />
        <Hero />
        <Philosophy />
        <OurServices />
        <More />
        <Project />
        <Contact />
      </main>
    </div>
  );
}
